In [1]:
import numpy as np

In [2]:
X = np.matrix([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1],
])

def nnf(W1, B1, W2, B2, thresh=0):
    # Layer 1
    Z = X * W1 + B1
    
    # Transfer function for z
    for i in range(Z.shape[0]):
        for j in range(Z.shape[1]):
            Z[i,j] = 1 if Z[i,j] > thresh else 0
            
    # Layer 2
    Y = Z * W2 + B2
    
    # Transfer function for y
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j] = 1 if Y[i,j] > 0 else 0
    
    return Y

In [3]:
# First
W1 = np.matrix([
        [-1.0, -1.0],
        [ 1.0,  1.0],
    ])
B1 = np.matrix([
        [-0.5,  1.5],
        [-0.5,  1.5],
        [-0.5,  1.5],
        [-0.5,  1.5],
    ])

W2 = np.matrix([
        [1, 1],
    ]).transpose()

B2 = np.matrix([
        -0.5, -0.5, -0.5, -0.5
    ]).transpose()

In [8]:
nnf(W1, B1, W2, B2, thresh=0)

matrix([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.]])

In [7]:
nnf(W1, B1, W2, B2, thresh=1)

matrix([[ 1.],
        [ 1.],
        [ 0.],
        [ 1.]])

In [9]:
# Second
W1 = np.matrix([
        [ 1.0, -1.0],
        [ 1.0, -1.0],
    ])
B1 = np.matrix([
        [-1.5,  0.5],
        [-1.5,  0.5],
        [-1.5,  0.5],
        [-1.5,  0.5],
    ])

W2 = np.matrix([
        [1, 1],
    ]).transpose()

B2 = np.matrix([
        -1.5, -1.5, -1.5, -1.5
    ]).transpose()

In [10]:
nnf(W1, B1, W2, B2, thresh=0)

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [11]:
nnf(W1, B1, W2, B2, thresh=1)

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [12]:
# Third
W1 = np.matrix([
        [ 1.0, -1.0],
        [ 1.0, -1.0],
    ])
B1 = np.matrix([
        [-1.5,  1.5],
        [-1.5,  1.5],
        [-1.5,  1.5],
        [-1.5,  1.5],
    ])

W2 = np.matrix([
        [1, 1],
    ]).transpose()

B2 = np.matrix([
        -0.5, -0.5, -0.5, -0.5
    ]).transpose()

In [13]:
nnf(W1, B1, W2, B2, thresh=0)

matrix([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.]])

In [14]:
nnf(W1, B1, W2, B2, thresh=1)

matrix([[ 1.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [15]:
# Fourth
W1 = np.matrix([
        [ 1.0, -1.0],
        [ 1.0, -1.0],
    ])
B1 = np.matrix([
        [-1.5,  0.5],
        [-1.5,  0.5],
        [-1.5,  0.5],
        [-1.5,  0.5],
    ])

W2 = np.matrix([
        [1, 1],
    ]).transpose()

B2 = np.matrix([
        -0.5, -0.5, -0.5, -0.5
    ]).transpose()

In [16]:
nnf(W1, B1, W2, B2, thresh=0)

matrix([[ 1.],
        [ 0.],
        [ 0.],
        [ 1.]])

In [17]:
nnf(W1, B1, W2, B2, thresh=1)

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [18]:
# Fifth
W1 = np.matrix([
        [ 1.0, -1.0],
        [ 1.0, -1.0],
    ])
B1 = np.matrix([
        [-1.5,  1.5],
        [-1.5,  1.5],
        [-1.5,  1.5],
        [-1.5,  1.5],
    ])

W2 = np.matrix([
        [1, 1],
    ]).transpose()

B2 = np.matrix([
        -1.5, -1.5, -1.5, -1.5
    ]).transpose()

In [19]:
nnf(W1, B1, W2, B2, thresh=0)

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [20]:
nnf(W1, B1, W2, B2, thresh=1)

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])